### ISSUE TITLE
[2] Support self-signed CA bundles

### ISSUE THREAD

**Issue by danielharr** [elastisys/ck8s-cluster#101]
Implement support for trusting a self-signed CA in our Kubernetes installations.
This is required to be able to fit compliantkubernetes in "private" PKIs.

**Suggestion for a way to verify this once done:**
Configure trust for the letsencrypt staging CA.
Successfully deploy a pod running a container from a Harbor instance that is serving a letsencrypt staging certificate.

**Comment by tordsson** [comment]
Supported by kubespray
