### ISSUE TITLE
Fix aws extra_tags variable

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#103]
The pipeline fails for aws since we added the aws extra_tags. We need to set this to a default value if it doesn't exists

ex. error
```
Error: Invalid function argument

  on modules/kubernetes-cluster/main.tf line 372, in resource "aws_instance" "master":
 369: 
 370: 
 371: 
 372:   }, var.extra_tags)
    |----------------
    | var.extra_tags is null

Invalid value for "maps" parameter: argument must not be null.
```

## Acceptance criteria

* Pipeline should not throw this error when ran

**Comment by cristiklein** [comment]
When reporting pipeline failures, please link to the run that fails. I can't find it, and this one ran. :)

https://github.com/elastisys/ck8s-cluster/runs/1362485979?check_suite_focus=true

**Comment by viktor-f** [comment]
He is talking about a pipeline in `ck8s-pipelines`.
This is the latest one https://github.com/elastisys/ck8s-pipelines/runs/1421620784?check_suite_focus=true
