### ISSUE TITLE
Release pipeline fails to build docker images

### ISSUE THREAD

**Issue by vanneback** [elastisys/ck8s-cluster#13]
The release pipeline fail everytime on build and push dockerfiles. e.g. https://github.com/elastisys/ck8s-cluster-old/actions/runs/248111401

This problem is because the action want a USERNAME PASSWORD set in secrets so it has credentials for pushing to dockerhub but those are not added in this repo.

**Comment by tordsson** [comment]
Deprecated by kubespray
