### ISSUE TITLE
How to handle security issues

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#14]
We should have a separate system for security related issues instead of public GitHub issues.
Initially it may be enough with a simple "contact us at this email address", but eventually we will also need a way to track these issues internally.

**Comment by tordsson** [comment]
Suggested solution:
- Add contact email address to readme
- tracking in private repo (ck8s wrapper repo right now), will likely add more internal repos...

**Comment by tordsson** [comment]
Do the same in the ck8s-apps repo, once this is OS:d
