### ISSUE TITLE
Support pre-existing networks

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#19]
Ck8s-cluster is currently very rigid in its network layout. It also depends a lot on the cloud provider and what they support. When possible, we create all networks, subnets, routers, etc. This all works well in a SaaS setting where we control everything and just expose the API to customers. However, it quickly becomes a problem when someone want to run ck8s together with other services (on-premise?) in the same network or at least have some control over what networks and subnets are used.

We already have 2 customers asking for or "working around" this in some way or another. If we want to [support VMware][1] or even bare metal this will be important to solve.

A first step could be to make the networks and subnets configurable in Terraform. Second, make it possible to reuse existing networks and subnets.

[1]: https://github.com/elastisys/ck8s/issues/644

**Comment by tordsson** [comment]
Deprecated by kubespray.
