### ISSUE TITLE
Private clusters

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#20]
We should make it possible to create "private" clusters where the Nodes do not have public IP addresses at all. Since we are boasting compliance we should probably make this default as well.

To make private clusters possible, we need to change the way we install Kubernetes. Currently we use direct ssh connections to every Node. With private IPs only, we would need to use a bastion host, VPN connection or similar to access the private network before we could connect to them. It could even be possible to do the whole setup using cloud-init, like CAPI does it.

**Comment by tordsson** [comment]
Supported by kubespray bastion host setup
