### ISSUE TITLE
[8] Move DNS management to separate repository

### ISSUE THREAD

**Issue by simonklb** [elastisys/ck8s-cluster#24]
Managing DNS records doesn't make much sense for standalone clusters without the apps. We should move this to a separate project and make it part of the wrapper instead of creating them as a part of the cluster deployment process.

**Comment by pettersv** [comment]
I had an issue setting up a cluster. dex auth was returning login succesful but kubelogin and ck8sdash returned 401. The error was tracked down the error to this file

https://github.com/elastisys/ck8s-cluster/blob/f1f2c79b0de620d9db35daaf6186d52af678eed0/ansible/templates/kubeadm-config.yaml.j2#L49

ECK_BASE_DOMAIN domain was blank so the oidc-issur-url was set to https://dex.

Seems related?
