### ISSUE TITLE
Exoscale: Switch from EIP to NLB

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#26]
Exoscale has [introduced Network Load Balancers][1].
We should check if we can get rid of the [hack][2] we currently use for internal loadbalancing, and even if that is not possible, we should switch from EIP to NLB for external traffic in order to get better load balancing (true round robin).

[1]: https://www.exoscale.com/syslog/network-load-balancer-release/
[2]: https://github.com/elastisys/ck8s-dev-docs/blob/master/2020-05-25-ha-control-plane.md#exoscale

**Comment by Xartos** [comment]
This isn't possible to use if we don't use instance pools according to the documentation.
Related issue elastisys/ck8s-cluster#81
