### ISSUE TITLE
Move S3 bucket management to apps

### ISSUE THREAD

**Issue by simonklb** [elastisys/ck8s-cluster#32]
As we are currently planning on making this repository work as a standalone tool it doesn't make much sense in creating a bunch of S3 buckets which will never be used.

I'm proposing to move the S3 bucket management to the apps repository instead. Any thoughts or opinions on the matter?

**Comment by Xartos** [comment]
I think that sounds reasonable, especially now when we are moving to a bootstrap step in the apps repo. I think it makes sense to have the S3 creation as a part of that.

**Comment by OlleLarsson** [comment]
closing in favor of https://github.com/elastisys/ck8s-cluster/issues/25
