### ISSUE TITLE
Unify naming of variables

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#34]
Right now there are some variables for the different providers ~that refers to the same info but the variable names are different.~

Example of this would be this one:
https://github.com/elastisys/ck8s-cluster/blob/e7d6d44a8c18a4d4da4a225f21311769dfb958dc/api/exoscale/secret.go#L10-L11

Here the names of the variables are kind of confusing. A suggestion here would be to change the name of `APIKey` to something like `ExoscaleAPIKey`.

This issue relates to elastisys/ck8s#500

**Comment by simonklb** [comment]
Related: https://github.com/elastisys/ck8s/issues/532

**Comment by tordsson** [comment]
Deprecated by kubespray
