### ISSUE TITLE
Binaries and other "non-config" included in config path

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#35]
Currently things like terraform plugin binaries and other similar things are stored under `.state` at the `CK8S_CONFIG_PATH`. This is problematic for Ops, since we want to use this path as a git repository.
As a workaround, I have used a `.gitignore` file with the following content:

```
.terraform
.terraform-tfe
```

This still allows the `.state/terraform-tfe.tfstate` to be versioned but keeps all plugins out of git. I'm not sure if this is the best solution but it seems simple and effective to me.

For reference, this is the content in `.state`:

```
❯ tree .state -a
.state
├── ansible_hosts_sc.ini
├── ansible_hosts_wc.ini
├── infra.json
├── kube_config_sc.yaml
├── kube_config_wc.yaml
├── s3cfg.ini
├── .terraform
│   ├── modules
│   │   └── modules.json
│   ├── plugins
│   │   └── linux_amd64
│   │       ├── lock.json
│   │       ├── terraform-provider-aws_v2.70.0_x4
│   │       └── terraform-provider-openstack_v1.30.0_x4
│   └── terraform.tfstate
├── .terraform-tfe
│   └── plugins
│       └── linux_amd64
│           ├── lock.json
│           └── terraform-provider-tfe_v0.18.0_x4
├── terraform-tfe.tfstate
└── terraform-tfe.tfstate.backup
```

**Comment by tordsson** [comment]
Deprecated by kubespray
