### ISSUE TITLE
Ansible still sometimes hangs when installing pip

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#36]
We previously had this issue and was thought to be fixed by this https://github.com/elastisys/ck8s-cluster/commit/9c6e89931dbfcb5439314f8a5f7cfeea01afead3
But this is apparently still an issue (maybe less frequent but still an issue). We need to find the root cause for this, since one solution could maybe just be to increase the async time and/or add some retries on the task.

**Comment by simonklb** [comment]
Could try replacing the Ansible Docker module with running `docker run` / `docker restart` directly as shell commands. This would eliminate the need for pip as well.
https://github.com/elastisys/ck8s-cluster/blob/master/ansible/roles/internal_lb/tasks/main.yml

**Comment by Xartos** [comment]
I got this error and it seems to be network related. One of the many duplicates of these errors were:

```
Cannot initiate the connection to ch-gva-2.clouds.archive.ubuntu.com:80 (2001:67c:1562::26). - connect (101: Network is unreachable) Cannot initiate the connection to ch-gva-2.clouds.archive.ubuntu.com:80 (2001:67c:1360:8001::35). - connect (101: Network is unreachable) Cannot initiate the connection to ch-gva-2.clouds.archive.ubuntu.com:80 (2001:67c:1562::29). - connect (101: Network is unreachable) Cannot initiate the connection to ch-gva-2.clouds.archive.ubuntu.com:80 (2001:67c:1360:8001::36). - connect (101: Network is unreachable)
```

So maybe we should disable ipv6 since it looks like that is a problem it's facing here.

**Comment by Xartos** [comment]
Have not seen this for a long time, reopen or create a new issue if this appears again

**Comment by lentzi90** [comment]
I'm still seeing this (twice yesterday) and it also happened in [this pipeline](https://github.com/elastisys/ck8s-pipelines/runs/1451520978?check_suite_focus=true#step:9:304).
Will create a PR with an attempt to retry installation instead of just waiting a long time.
