### ISSUE TITLE
Import workspace into tfe state if exists

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#37]
When the pipeline have ran and not deleted the remote workspace. If you do "rerun all jobs" it will fail since the workspace is not deleted and the state is local, so it's gone. (or it is actually uploaded as an artifact, so not completly gone)

The pipeline should be able to re-run without having this issue. Now you need to manually clean up the workspace (easily done with `ck8s internal terraform destroy` with the pipeline name in the config and then remove the workspace manually.

Some suggested solutions would be to try to recreate the state by importing the workspace, this could possibly be dangerous if you accentually names your workspace the same as someone else.
Or if you could download the artifact in the pipeline as the first step. Don't know if this is possible, since the artifact is not present first time you run the pipeline. This behaviour needs to be investigated

**Comment by tordsson** [comment]
deprecated by kubespray.
