### ISSUE TITLE
terraform invalid index errors

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#4]
It happens quite frequently that a `terraform destroy` fails or is interrupted in some way. When this happens, it should be safe to rerun `terraform destroy` and it should manage to remove the remaining resources. However, we currently reference some objects directly as "keys" in other values, which means that of the object is gone terraform will fail due to the "invalid index" (the missing object that was used as key.

It looks like this in the logs:
```
Plan: 0 to add, 0 to change, 8 to destroy.
Do you really want to destroy all resources in workspace "safespring-dev-256675358"?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.
  Enter a value: yes
Error: Invalid index
  on ../modules/openstack/vm/output.tf line 23, in output "instance_ips":
  23:       "public_ip"  = openstack_compute_floatingip_v2.fip[key].address
    |----------------
    | openstack_compute_floatingip_v2.fip is object with no attributes
The given key does not identify an element in this collection value.
```

In this specific case, terraform tries to fill the output values `public_ip` with the address of a floating IP, but the floating IP is already gone.
One way to fix this is to change the line to look like this:
```
"public_ip"  = lookup(openstack_compute_floatingip_v2.fip, key, {address: ""}).address
```
Now we try to lookup the address and sets the default to `""` in case it is missing.

To solve this issue, do the following:

- Find all places in the terraform code where we reference elements in collections in this way
- Fix them e.g. by setting defaults or avoid references completely if possible

**Comment by tordsson** [comment]
Deprecated by kubespray
