### ISSUE TITLE
Dont get error when environment vars are set

### ISSUE THREAD

**Issue by vanneback** [elastisys/ck8s-cluster#40]
For example this command.
```
./dist/ck8s_linux_amd64 init  ev exoscale
Error: CK8S_ENVIRONMENT_NAME is deprecated, use positional arg
```
Should not error just because the environment var is set as long as the command specifies an environment.
same goes for
- CK8S_CLOUD_PROVIDER
- CK8S_ENVIRONMENT_NAME
- CK8S_PGP_UID

**Comment by Xartos** [comment]
This was a decicion that was made since it could be ambigous to which parameter is read. That you think that it will use the `CK8S_ENVIRONMENT_NAME` but instead it uses positional.
Just a fail safe for when you switch over from the old cli.

**Comment by vanneback** [comment]
The apps repo still needs theese variables set to init. Then it becomes quite tedious usage if you then need to unset them. Just thought it was quite backwards to actually exit because a variable was set and it would make more sense to fail if the positionals are unset. But maybe it makes sense.

**Comment by Xartos** [comment]
Why do apps need it? Cant it use it from the config file? It feels like it would be very prone to issues if you need to set it twice in different ways.

**Comment by simonklb** [comment]
Just to clarify a bit, the reasoning here is that flags will have environment variables while positional arguments don't. And like @Xartos wrote, to not confuse users coming from the old CLI we opted for a very clear "this is no longer used" message to stop people from using it.

We could convert the environment/cluster name to a flag, but that feels wrong imo. Let's discuss how to unify the two repos offline.

**Comment by simonklb** [comment]
Feel free to re-open if this is not an acceptable answer.
