### ISSUE TITLE
Ansible using some envs that the gocli doesn't pass

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#41]
Some of the ansible files are using `lookup('env' ...)` which isn't considered in the cli.

Good example of this that was needed to be fixed was https://github.com/elastisys/ck8s-cluster-old/pull/15

We need to either support all the envs that ansible is using in its scripts or we need to move them to the inventory file _(what I would prefer)_

**Comment by tordsson** [comment]
Deprecated by kubespray
