### ISSUE TITLE
Remove terraform defaults that exists in config

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#45]
There's default values in the terraform code that could be grabbed from the cluster config.

There's probably more variables that can be fixed but a great example of this would be:
https://github.com/elastisys/ck8s-cluster/blob/f1f2c79b0de620d9db35daaf6186d52af678eed0/terraform/exoscale/modules/kubernetes-cluster/variables.tf#L38-L40

Which is also present here:

https://github.com/elastisys/ck8s-cluster/blob/f1f2c79b0de620d9db35daaf6186d52af678eed0/api/exoscale/cluster.go#L39

These need to match for calico to work, and should be fixed.

## Suggested solution

Expose this value as a variable in the root module for each cloud provider and add the configured value as a terraform variable here:

https://github.com/elastisys/ck8s-cluster/blob/f1f2c79b0de620d9db35daaf6186d52af678eed0/api/exoscale/cluster.go#L81-L86

**Comment by tordsson** [comment]
Deprecated by kubespray
