### ISSUE TITLE
Reduce master node remove/reset delay

### ISSUE THREAD

**Issue by simonklb** [elastisys/ck8s-cluster#46]
When resetting or removing a machine we currently wait for the maximum time a master node can be kept in the load balancer target pool before it times out. This is a very long wait because of CityCloud's long health check settings:

https://github.com/elastisys/ck8s-cluster/blob/2be9523317ea1e389141be68d4b63f9225f050e3/client/cluster.go#L438-L442

1. Can CityCloud's settings be shorter? Is there any reason to keep the timeout and delay that long?
2. Can we directly access the different load balancer services and force remove the removed master machine from the pool? If not, let's add the timeout and delay to the cluster configuration so that we have a single source of truth and different wait times for different providers.

**Comment by tordsson** [comment]
Deprecated by kubespray
