### ISSUE TITLE
Internal server error getting networks from Safespring

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#47]
The pipeline sometimes fails on the terraform apply due to various errors. In this particular instance it failed to get networks from the Safespring API:

```
Error: Error trying to get network information from the Network API: Unable to retrieve networks from the Network API: Internal Server Error

  on ../modules/openstack/vm/main.tf line 22, in resource "openstack_compute_instance_v2" "instance":
  22: resource "openstack_compute_instance_v2" "instance" {


Error: error applying Terraform config: error while executing `terraform apply -var-file /ck8s-config/tfvars.json -target module.service_cluster -auto-approve`: 1 error occurred:
	* exit status 1
```

This is part of the [pipeline stability epic](https://github.com/elastisys/ck8s-pipelines/issues/5) to try to hunt down and squash pipeline bugs.
Note that this is a flake, it is not happening every time. In other words, to fix this issue we will probably have to consider retries or similar.

**Comment by tordsson** [comment]
Deprecated by kubespray
