### ISSUE TITLE
Create step for cleaning up kubernetes without failing

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#52]
Now the destroy command will fail when kubernetes cleanup fails. This might not be what we want for pipelines, since that would leave some unattended resources in the cloud which needs to be cleaned up *(It would be less if it could delete the cluster and only leave a couple of kubernetes resources)*

## Suggested solution

Add a subcommand that runs the kubernetes cleanup procedure but doesn't fail on error. This could then be used by pipelines which then runs destroy with `--kubernetes-cleanup=false` and thus remove as much resources as it can.

**Comment by tordsson** [comment]
Deprecated by kubespray
