### ISSUE TITLE
Unify and improve security groups

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#58]
The security groups we set up currently differ between the cloud providers. Sometimes this is because of actual differences in how the ingress or load balancers work, but some of the differences do not really have a good reason to exist.
We should unify the rules as far as possible to make it easier to document and reason about what network traffic we allow.
While doing this, it would be great to minimize the traffic we allow.

Some examples on things that probably should change:
- We allow [all traffic between control plane and workers on openstack](https://github.com/elastisys/ck8s-cluster/blob/master/terraform/modules/openstack/secgroups/main.tf#L24)
- Exoscale doesn't have a "cluster" group but openstack does
- Some older rules still allow traffic directly from the internet to the kubernetes API or to workers even though all traffic should go trough the load balancers (except for NodePort traffic).

This is quite stronly related to #20 so it would make sense to synchronize any work on these two issues.

**Comment by tordsson** [comment]
Deprecated by kubespray
