### ISSUE TITLE
Switch to external OpenStack cloud controller manager

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#70]
We are currently using the legacy in-tree cloud provider for OpenStack.
The old in-tree providers are slowly being deprecated and it is getting increasingly hard to find any documentation for them.
Therefore we should switch to the [external OpenStack cloud controller manager](https://github.com/kubernetes/cloud-provider-openstack) instead.

Definition of done: It is possible to run ck8s-cluster on OpenStack using the external cloud provider implementation AND there is a migration path for switching from the in-tree provider to the external one.

**Comment by tordsson** [comment]
No information available about affected k8s version(s) as of 2020-10-08...

**Comment by tordsson** [comment]
Deprecated by kubespray
