### ISSUE TITLE
Version info for CLI

### ISSUE THREAD

**Issue by pettersv** [elastisys/ck8s-cluster#71]
It would be nice if the cli would display something like "This is ck8s cli version x.x.x for compliant kubernetes x.x.x, continue y/n" when running init, this would prevent some mistakes caused by fat fingers when handling multiple clusters of different versions.

**Comment by Xartos** [comment]
It would also be nice if the version flag/command also included the git commit as well as the version number it was built from.

Something like:
```
$ ck8s version
version: v0.6.1
commit: abcdef
```

**Comment by simonklb** [comment]
A `--version` flag exists but I do like the idea of including the commit hash as well.
```
% ./dist/ck8s_linux_amd64 --version
ck8s version v0.6.0
```

**Comment by tordsson** [comment]
Deprecated by kubespray
