### ISSUE TITLE
[1] Investigate update ansible

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#8]
We are currently on a quite old version of ansible (v2.5). It would be nice to update it to something newer to stay closer to the upstream and get access to new functionality and bug fixes.

There are likely no code changes needed for this as ansible is mostly backwards compatible, but we should think about how we install ansible.
Two popular options are to use the [ansible PPA](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu) or [pip](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-with-pip) (which can be used in a python venv).
As we now wrap everything in golang, we may also consider a [go library for ansible](https://github.com/apenella/go-ansible).

Definition of done: A new issue is created with suggested path forward (e.g. update to version vX.Y, use Z installation method).

**Comment by geoff-elastisys** [comment]
Created a doc here: https://docs.google.com/document/d/1EuBlsubkl3h3nitYi2eIt_GjFH8pl_jTH8rjQf5i_sM/edit?usp=sharing

<tl:dr>
Upgrade to latest stable - version 2.10
Use ppa - only ubuntu/debian supported
Script to check os version - if not deb, give warning, error out

**Comment by lentzi90** [comment]
Good job! I think we can close this now :slightly_smiling_face:
