### ISSUE TITLE
Upgrade terraform to v0.13

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/ck8s-cluster#85]
Beta releases of 0.14 are starting to pop-up and I think it would make sense to try and upgrade our terraform dependecy to the current 0.13 release sometime in the near future as to not lag too far behind.

Upgrade guide https://www.terraform.io/upgrade-guides/0-13.html

**Comment by simonklb** [comment]
I'd ideally see us utilize the module iterator, however that would make it backwards incompatible with current state.

**Comment by tordsson** [comment]
Deprecated by kubespray
