### ISSUE TITLE
Update Exoscale Terraform provider

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#86]
We are currently running version 0.12 of the Exoscale Terraform provider, while version 0.20 is available. We should try to stay up to date with the upstream in order to avoid hard transitions later when forced to upgrade.

**Comment by lentzi90** [comment]
I should have been clearer in the description. This will probably require a bit of work since there has been multiple deprecations and changes, so it will most likely be more than a "15 min issue". :slightly_smiling_face: 

Check the changelog here: https://github.com/exoscale/terraform-provider-exoscale/blob/v0.20.0/CHANGELOG.md

**Comment by Pradyumnakashyap** [comment]
Tried bumping the Exoscale-Terraform version in the main.tf and set up the cluster, I did not get any errors. Probably because deprecation count is just one and is unrelated to what we use. But do let me know if I am missing something :)

**Comment by Pradyumnakashyap** [comment]
I have tried bumping up the version until 0.20 and applied it to set up a cluster (no code update required), as long as we don't move the Terraform version to =>0.13, it works fine. But if we are already moving to Terraform v13 (based on another card in prioritization board), then I would say we better wait for that and follow up with this behind the Terraform upgrade as it might need some change in code. 
- https://registry.terraform.io/providers/exoscale/exoscale/latest/docs

**Comment by cristiklein** [comment]
This was done as part of upstreaming the Exoscale Terraform scripts to Kubespray: https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/terraform/exoscale/versions.tf#L5
