### ISSUE TITLE
Investigate how to add azure object storage

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#92]
At the moment we don't support azure object storage (since it does not speak s3 directly)
We should investigate how we should implement support for this for all our services.

One solution would be to use minio to proxy the traffic https://cloudblogs.microsoft.com/opensource/2017/11/09/s3cmd-amazon-s3-compatible-apps-azure-storage/

## Acceptance criteria 

* Investigate how to add azure s3 support and create issues to match

**Comment by tordsson** [comment]
Deprecated by https://github.com/elastisys/compliantkubernetes-apps/issues/132
