### ISSUE TITLE
Init fails on Safespring and Citycloud

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#93]
Initialization on Safespring fails due to OIDCIssuerURL, AWSAccessKeyID, AWSSecretAccessKey, AWSDNSZoneID, AWSDNSRoleARN missing.

Another (very minor thing) is that the workload cluster loadbalancer IP is missing in `infra.json`. If it is a quick and simple fix, it may be worth to squeeze it in at the same time.

**Comment by viktor-f** [comment]
The loadbalancer IP is important now, since we need that info to create DNS records.
